### ISSUE TITLE
Parameter validation - allowed value is not allowed

### ISSUE THREAD

**Issue by hampos** [KinkyDesign/JaqpotQuattroUI#80]
```
Error: Parameter with id: 'confidence' has a value not found in allowed values.

org.jaqpot.core.service.exceptions.parameter.ParameterRangeException: Parameter with id: 'confidence' has a value not found in allowed values. at org.jaqpot.core.service.validator.ParameterValidator.checkAllowedValues(ParameterValidator.java:157) at org.jaqpot.core.service.validator.ParameterValidator.validate(ParameterValidator.java:96) at org.jaqpot.core.service.resource.AlgorithmResource.trainModel(AlgorithmResource.java:341) at 
```

confidence allowed values was `[0,1]`
request had `confidence:1`

the input was parsed as Double 1.0 and comparison failed

**Comment by AValsamis** [comment]
Commit with #failname [Fix #KinkyDesign/JaqpotQuattroUI#80](https://github.com/KinkyDesign/JaqpotQuattro/commit/068b2ba7c77469fe43f94f97bc9f23a2ffbb2a26) fixes this.
